export {default as Login} from './Login.vue'
export {default as Entries} from './Entries.vue'
export {default as Home} from './Home.vue'
export {default as Entry} from './Entry.vue'
export {default as EntryEdit} from './EntryEdit.vue'
export {default as Dashboard} from './Dashboard.vue'